### ISSUE TITLE
Remove JourneyState collection (couple JourneyState with MonitoredTrip as field)

### ISSUE THREAD

**Issue by landonreed** [ibi-group/otp-middleware#107]
JourneyState was moved to its own collection during the initial coding of the MonitoredTrip features, but we have since determined that it should be returned as part of the getMonitoredTrip endpoint. So, per discussion on technical call, we have decided to move this to be a field on `MonitoredTrip`. Some JourneyState fields may need to be ignored with `@JsonIgnore` annotations that do not need to be shared with clients.

**Comment by binh-dam-ibigroup** [comment]
Closing. This was handled by #97.
