### ISSUE TITLE
Itinerary check returns no monitorable days

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [ibi-group/otp-middleware#172]
## Observed behavior

When saving one of the transit itineraries for monitoring, no monitorable days are returned.

https://atl-rides.ibi-transit.com/#/?fromPlace=%2833.784854448488915%2C-84.37362670898439%29%3A%3A33.784854448488915%2C-84.37362670898439&toPlace=217%20Thirkield%20Ave%20SW%2C%20Atlanta%2C%20GA%2030315-3500%2C%20United%20States%3A%3A33.714059324224124%2C-84.39285278320314&date=2022-07-15&time=16%3A41&arriveBy=false&mode=WALK%2CBUS%2CSUBWAY%2CTRAM%2CFLEX_EGRESS%2CFLEX_ACCESS%2CFLEX_DIRECT&showIntermediateStops=true&walkSpeed=1.34&ignoreRealtimeUpdates=true&wheelchair=true&numItineraries=3&otherThanPreferredRoutesPenalty=900

## Expected behavior

There should be monitorable days returned by the `checkitinerary` endpoint.

## Steps to reproduce the problem

While signed in, perform the check above and attempt to save one of the transit trips for monitoring.
Observe that all days are crossed out, indicating no day can be monitored.

## Any special notes on configuration used

NA

## Version of otp-middleware and/or OpenTripPlanner if applicable (exact commit hash or branch name)

Current dev version of otp-middleware.

**Comment by JymDyerIBI** [comment]
At this writing, this problem has been fixed by changes on `otp-middleware`'s `dev` branch when queries come from `otp-react-redux`'s `middleware-graphql` branch.

The fromPlace is happier as: "Lake Clara Meer, Midtown, Atlanta" and the toPlace is "217 Thirkield Ave SW, Atlanta, South Atlanta, Georgia" with multiple weekdays in September 2024.

**Comment by binh-dam-ibigroup** [comment]
Addressed by #243.
