### ISSUE TITLE
Middleware design: Proxy just OTP plan endpoint or all OTP endpoints?

### ISSUE THREAD

**Issue by landonreed** [ibi-group/otp-middleware#26]
I wonder if instead of just serving as a proxy for the `/plan` endpoint, we also want to serve as proxy for all OTP endpoints. We would then only post-process the plan responses (for storing trip history/summary), but that could simplify the configuration for the UI (we would have only one "OTP" server rather than splitting up things between "plan" and other endpoints). @evansiroky or @binh-dam-ibigroup, thoughts?

_Originally posted by @landonreed in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDE2ODY1Mjcx/timeline/more_items_

**Comment by br648** [comment]
Issue addressed in this PR: https://github.com/ibi-group/otp-middleware/pull/31
