### ISSUE TITLE
Auth0 redirect to new account setup after email verification

### ISSUE THREAD

**Issue by landonreed** [ibi-group/otp-middleware#63]
During sign up for new OTP users, Auth0 provides a way to redirect users to the OTP UI, but because the site is built as a single page app (SPA) directing to the correct path doesn't quite work properly. Fortunately, this is well-documented and Auth0 has a fix that includes adding a server-side endpoint to handle the redirect: https://auth0.com/docs/auth0-email-services/customize-email-templates#dynamic-redirect-to-urls. The endpoint (in node.js) looks like this:

```javascript
var express = require('express');
var router = express.Router();
var qs = require('qs'); // to read query string params and stringify them

router.get('/register', function(req, res, next) {
  var route = req.query.route; // retrieve the route param that contains the SPA client side route user needs to be redirected to.

  delete req.query.route; // remove it from query params.
  res.redirect('http://localhost:3000/#/' + route + '?' +  qs.stringify(req.query)); // Send a 302 redirect for the expected route
});

module.exports = router;
```

We should add an endpoint for this to improve the sign up. It should probably account for signups for both OTP users (otp-react-redux) and API users (otp-admin-ui).

**Comment by br648** [comment]
PR: https://github.com/ibi-group/otp-middleware/pull/76

**Comment by br648** [comment]
This has been addressed and merged into the dev branch.

**Comment by br648** [comment]
Complete.
