### ISSUE TITLE
Should deleting OtpUser also delete that user's MonitoredTrip, TripRequest, and TripSummary?

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [ibi-group/otp-middleware#80]
## Observed behavior

While reviewing [this file](https://github.com/ibi-group/otp-middleware/blob/b6c3f5ba0fd06a5dc091e4485f70739201584372/src/test/java/org/opentripplanner/middleware/persistence/TripHistoryPersistenceTest.java#L52), I'm realizing that upon deleting an `OtpUser`, we don't have a `preDeleteHook` to delete the following associated entities:
- `MonitoredTrip`,
- `TripRequest`,
- `TripSummary`.

Should we?

**Comment by landonreed** [comment]
We just handled this in #64, did we not?

https://github.com/ibi-group/otp-middleware/blob/9b9d54a17b9f5113272575b5639644de1f4159ba/src/main/java/org/opentripplanner/middleware/models/OtpUser.java#L50-L65

**Comment by binh-dam-ibigroup** [comment]
Thanks, so that is probably redundant code I saw in #78.
