### ISSUE TITLE
Requesting Monitored Trips from otp-rr with email used for both admin and OtpUser causes all monitored Trips to be returned

### ISSUE THREAD

**Issue by landonreed** [ibi-group/otp-middleware#81]
Steps to reproduce:

1. Create admin account (if not exists) with the same email address for an OtpUser that already exists.
2. Log into https://fdot-otp.ibi-transit.com/
3. View your trips.
4. Trips delivered will be full list rather than filtered list for user.

I think this is somewhat related to the work that @br648 is looking to do with the Auth refactor (disassociating ApiUser from Auth0). Effectively, we need to update the endpoint (or add a new one) for requesting a list of monitored trips to include a `userId` param or query param.

**Comment by br648** [comment]
@landonreed the way this is written at the moment an admin user can get a list of any objects without additional checks. This still applies under the work I'm doing with ApiUser and Auth0. In order for admin users to have unrestricted access to objects (if this is still required) I think the user account being created should be rejected if the email address is already in use. I could implement a check into the PR I'm working on. Thoughts?

**Comment by landonreed** [comment]
Per discussion with team, approach will be to use `userId` query param to filter the list of monitored trips (or other entity). However, if that is not provided, the conditional checks will come into play (admin, api user, etc.).

**Comment by binh-dam-ibigroup** [comment]
Closing this issue. It was fixed by #84.
