### ISSUE TITLE
Unable to send notification SMS

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [ibi-group/otp-middleware#92]
## Observed behavior

When a user signs up for monitored trip notifications via SMS, no SMS are sent to the user. (When the same user chooses email for notifications, emails are sent.). Moreover, the following error is reported in the log:

```log
[34mINFO [0;39m 2020-11-02T16:11:05.326 [33m[Thread-40][0;39m [34mo.o.m.t.jobs.CheckMonitoredTrip(CheckMonitoredTrip.java:236)[0;39m [33m[Trip ID: 8e70a19f-bd0a-4857-bef8-9714206f8d74][0;39m Sending notification '80th-Madison Notification' to user 894568fe-c47e-4cd3-a8ff-cd386ddaadae
[34mINFO [0;39m 2020-11-02T16:11:05.465 [33m[pool-1-thread-2][0;39m [34mo.o.m.persistence.TypedPersistence(TypedPersistence.java:271)[0;39m [33m[0;39m Deleted 13 objects of type BugsnagProject
[1;31mERROR[0;39m 2020-11-02T16:11:05.654 [33m[Thread-40][0;39m [34mo.o.m.utils.NotificationUtils(NotificationUtils.java:65)[0;39m [33m[Trip ID: 8e70a19f-bd0a-4857-bef8-9714206f8d74][0;39m Could not create SMS
com.twilio.exception.ApiException: The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.
	at com.twilio.rest.api.v2010.account.MessageCreator.create(MessageCreator.java:509)
	at com.twilio.rest.api.v2010.account.MessageCreator.create(MessageCreator.java:25)
	at com.twilio.base.Creator.create(Creator.java:45)
	at org.opentripplanner.middleware.utils.NotificationUtils.sendSMS(NotificationUtils.java:60)
	at org.opentripplanner.middleware.tripMonitor.jobs.CheckMonitoredTrip.sendNotifications(CheckMonitoredTrip.java:242)
	at org.opentripplanner.middleware.tripMonitor.jobs.CheckMonitoredTrip.doRun(CheckMonitoredTrip.java:122)
	at org.opentripplanner.middleware.tripMonitor.jobs.CheckMonitoredTrip.run(CheckMonitoredTrip.java:92)
	at org.opentripplanner.middleware.tripMonitor.jobs.TripAnalyzer.run(TripAnalyzer.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

## Expected behavior

An SMS should be sent to the user for the trip notification.

## Steps to reproduce the problem

1. Log in in MOD UI
2. Set your notification preferences to email.
3. Plan a trip
4. Pick one of the suggested itineraries, click "Save trip" or "Save this option".
5. Check you receive an email about your trip.
6. Change your notification preference to SMS, and verify the phone number.
7. Wait for the SMS (e.g. at the same time next day.)

## Version of otp-middleware and/or OpenTripPlanner if applicable (exact commit hash or branch name)

Current `dev` branch of OTP-middleware and OTP-RR.

**Comment by landonreed** [comment]
@binh-dam-ibigroup, I think we're missing a step in the verify process. After we successfully verify by code, I think we need to make a call to this endpoint: https://www.twilio.com/docs/voice/api/outgoing-caller-ids#add-an-outgoing-caller-id (or maybe use that endpoint instead of the one we have in place?).

**Comment by binh-dam-ibigroup** [comment]
Closing this issue now following changes to twilio account.
